// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Netcool.Core.EfCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Netcool.Core.Migrations
{
    [DbContext(typeof(NetcoolDbContext))]
    partial class NetcoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Netcool.Api.Core.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreateUserId");

                    b.Property<DateTime?>("DeleteTime");

                    b.Property<int?>("DeleteUserId");

                    b.Property<int>("Gender");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
